development:
  adapter: postgresql
  encoding: unicode
  database: buala_development
  host: localhost
  pool: 5
  username: buala
  password: buala

test: &test
  adapter: postgresql
  encoding: unicode
  database: buala_test
  host: localhost
  pool: 5
  username: buala
  password: buala

production:
  adapter: postgresql
  encoding: unicode
  database: buala_production
  host: localhost
  pool: 5
  username: buala
  password: buala
cucumber:
  <<: *test